language: node_js
env:
  - COVERALLS_SERVICE_NAME=travis-ci COVERALLS_REPO_TOKEN=sJqMI2yeTeJvIfcf3JxZQKHsEx630XvaN
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
  - "iojs-v1.0.4"
after_success:
  - "npm run cover"